# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a54ffc633ea23e0b828e769fe8a7f3935b21dc7ea848908dff1cd254c950e5b42cb21e34ff382453ab764e4d1ba7ab8b527226aae83a297aabefe98f37f26133

test:
  secret_key_base: 8298ffe4e664e31d806599fe12ef2cf7675d97e07f3c9b8c50cefc5f067ddfd69705217000d8e5c5c946d962c2f13eceac1b0cc2d0f0f142d07270c0a76241c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
